### ISSUE TITLE
pinger.OnRecv no timeout packet

### ISSUE THREAD

**Issue by SurtursRevenge** [go-ping/ping#87] opened 2020-05-13 23:27 UTC
Hello,

maybe i am getting this wrong. I want to print out the packet rtt which works fine with the onrecv function but i also want to print out when the ping times out. 
How would i get the information if there was a timeout ?

Best regards

**Comment by bestoml** [comment] 2021-02-02 01:49
The timeout mechanism in this project is timeout for all the packets. For example, if you set 100 count and 10s timeout. The timeout is for the sum of 100 counts, doesn't for 1 count.

**Comment by CHTJonas** [comment] 2021-02-08 12:07
Dupe of #50.

**Closed** 2021-02-08 12:08 UTC
Labels: duplicate
