### ISSUE TITLE
ipv6 shorthand notation causes setsockopt: invalid argument as root

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [go-ping/ping#122] opened 2020-11-23 08:32 UTC
Running an application to ping a bunch of ip addresses works perfectly as user, but running this exact same application as root causes an error: "setsockopt: invalid argument".

Looking at the addresses it fails at: 2001:41d0:601:1100::cf2

My guess: Something goes wrong with the parsing of the shorthand IPv6 notation?

**Comment by SuperQ** [comment] 2020-11-23 08:45
If you expand the address to `2001:41d0:601:1100:0:0:0:cf2` does it work? I was unable to reproduce the problem, can you give more details? What platform are you building on? What exactly are you building?

**Comment by CHTJonas** [comment] 2021-02-01 23:43
I'm going to close this since we cannot replicate it ourselves and there's been no reply for a while. @MathiasDeWeerdt if you can provide a reproducible example then we can reopen and investigate but we are using Go's standard libraries for parsing IPv4 and IPv6 addresses.

**Closed by CHTJonas** 2021-02-01 23:43 UTC
