### ISSUE TITLE
Deserialisation issue on Windows

### ISSUE THREAD

**Issue by lifeblood** [go-ping/ping#143] opened 2021-02-09 02:36 UTC
PING www.google.com (192.217.24.68):

--- www.google.com ping statistics ---
1 packets transmitted, 0 packets received, 0 duplicates, 100% packet loss
round-trip min/avg/max/stddev = 0s/0s/0s/0s

**Comment by CHTJonas** [comment] 2021-02-09 08:28
Can you please include some code that reproduces this?

\```go
you can put your code inside three backticks like so
and it will auto-format it nicely
\```

**Comment by lifeblood** [comment] 2021-02-09 08:31
```go
func DoPing(target string, t int) {
	timeout := time.Second * time.Duration(t)
	interval := time.Second
	count := -1
	privileged := true
	flag.Usage = func() {
		fmt.Print(usage)
	}
	flag.Parse()

	if flag.NArg() == 0 {
		flag.Usage()
		return
	}

	host := GetHost(target)
	pinger, err := ping.NewPinger(host)
	if err != nil {
		fmt.Printf("ERROR: %s\n", err.Error())
		return
	}

	// listen for ctrl-C signal
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		for range c {
			pinger.Stop()
		}
	}()

	pinger.OnRecv = func(pkt *ping.Packet) {
		fmt.Printf("%d bytes from %s: icmp_seq=%d time=%v ttl=%v\n",
			pkt.Nbytes, pkt.IPAddr, pkt.Seq, pkt.Rtt, pkt.Ttl)
	}
	pinger.OnDuplicateRecv = func(pkt *ping.Packet) {
		fmt.Printf("%d bytes from %s: icmp_seq=%d time=%v ttl=%v (DUP!)\n",
			pkt.Nbytes, pkt.IPAddr, pkt.Seq, pkt.Rtt, pkt.Ttl)
	}
	pinger.OnFinish = func(stats *ping.Statistics) {
		fmt.Printf("\n--- %s ping statistics ---\n", stats.Addr)
		fmt.Printf("%d packets transmitted, %d packets received, %d duplicates, %v%% packet loss\n",
			stats.PacketsSent, stats.PacketsRecv, stats.PacketsRecvDuplicates, stats.PacketLoss)
		fmt.Printf("round-trip min/avg/max/stddev = %v/%v/%v/%v\n",
			stats.MinRtt, stats.AvgRtt, stats.MaxRtt, stats.StdDevRtt)
	}

	pinger.Count = count
	pinger.Interval = interval
	pinger.Timeout = timeout
	pinger.SetPrivileged(privileged)

	fmt.Printf("PING %s (%s):\n", pinger.Addr(), pinger.IPAddr())
	err = pinger.Run()
	if err != nil {
		fmt.Printf("Failed to ping target host: %s", err)
	}
}
```

**Comment by scientiacoder** [comment] 2021-02-09 14:02
I changed the variable ```count``` to a positive integer number cause it indicates pinger to stop after sending(and receiving) ```Count``` echo packets as well as this code in ```recvICMP``` function:
```go
default:
	// ICMP messages have an 8-byte header.
	bytes := make([]byte, p.Size+8)    // change p.Size + 8 to a larger value like 512
```
to
```
default:
	// ICMP messages have an 8-byte header.
	bytes := make([]byte, 512)    // change p.Size + 8 to a larger value
```
and it works well on my windows 10 laptop.

**Comment by lifeblood** [comment] 2021-02-09 14:58
> I changed this code in `recvICMP` function if you are importing go-ping as local packages:
> 
> ```go
> default:
> 	// ICMP messages have an 8-byte header.
> 	bytes := make([]byte, p.Size+8)    // change p.Size + 8 to a larger value like 512
> ```
> 
> to
> 
> ```
> default:
> 	// ICMP messages have an 8-byte header.
> 	bytes := make([]byte, 512)    // change p.Size + 8 to a larger value
> ```
> 
> and it works well on my windows 10 laptop.

When I change it, the program can return recv message, but not have ttl value.


PING www.google.com (172.217.31.228):
24 bytes from 172.217.31.228: icmp_seq=0 time=93.7401ms ttl=0
24 bytes from 172.217.31.228: icmp_seq=1 time=84.5403ms ttl=0
24 bytes from 172.217.31.228: icmp_seq=2 time=86.0818ms ttl=0

--- www.google.com ping statistics ---
3 packets transmitted, 3 packets received, 0 duplicates, 0% packet loss
round-trip min/avg/max/stddev = 84.5403ms/88.120733ms/93.7401ms/4.023018ms

**Comment by scientiacoder** [comment] 2021-02-09 15:50
Found some old issues about TTLs on the Windows platform, #105, #108. Hope this can help...

**Comment by CHTJonas** [comment] 2021-02-09 18:27
Thanks for the repro code @lifeblood! I can replicate reliably and have a fix that I'll submit in a PR shortly.

@scientiacoder using a fixed size of 512 bytes is sub-optimal for a couple of reasons (see #137 and #138).

The real issue here is some kind of strange Windows-only incompatibility in the underlying Go standard libraries -- if you test this on Linux or macOS then it works fine. But for some reason when we run on Windows `(*ipv4.PacketConn).ReadFrom([]byte)` wants to deserialise a full IP packet rather than just the payload. But we can work around this...

The lack of TTLs on Windows is a known upstream issue that's out of scope for us here -- there's nothing we can do to fix it ourselves I'm afraid.

**Comment by lifeblood** [comment] 2021-02-10 01:15
ping www.google.com
PING www.google.com (172.217.31.228) 56(84) bytes of data.
64 bytes from hkg07s28-in-f4.1e100.net (172.217.31.228): icmp_seq=1 ttl=55 time=20.4 ms
64 bytes from hkg07s28-in-f4.1e100.net (172.217.31.228): icmp_seq=2 ttl=55 time=20.7 ms
64 bytes from hkg07s28-in-f4.1e100.net (172.217.31.228): icmp_seq=3 ttl=55 time=20.6 ms
64 bytes from hkg07s28-in-f4.1e100.net (172.217.31.228): icmp_seq=4 ttl=55 time=29.4 ms
64 bytes from hkg07s28-in-f4.1e100.net (172.217.31.228): icmp_seq=5 ttl=55 time=20.6 ms

================================================================

In addition，go-ping can not get the CNAME address of the ping domain.

**Comment by CHTJonas** [comment] 2021-02-10 09:59
The code at `cmd/ping/ping.go` is intended as a demo only and not a wholesale replacement of `/bin/ping` on *NIX systems or `C:\Windows\System32\PING.EXE` on Windows.

By "get the CNAME address of the ping domain" I presume you mean performing a reverse lookup by querying the `arpa.` DNS zone for PTR records? If so then I think this is out of scope for a simple ICMP library. My opinion is that the downstream application should handle doing the DNS bit.

**Comment by CHTJonas** [comment] 2021-02-16 21:05
If you update to the latest commit on `master` this should now be fixed.

**Closed** 2021-02-16 21:04 UTC
Labels: bug
