### ISSUE TITLE
[features request] timeout as error

### ISSUE THREAD

**Issue by yxxhero** [go-ping/ping#165] opened 2021-04-22 09:06 UTC
[features request] timeout as error

**Comment by SuperQ** [comment] 2021-04-22 09:27
This seems like a duplicate of https://github.com/go-ping/ping/issues/50

**Comment by yxxhero** [comment] 2021-04-22 09:47
Can I continue https://github.com/go-ping/ping/issues/50 work?  @SuperQ

**Comment by SuperQ** [comment] 2021-04-22 10:35
Yes, we need some foudnations as @CHTJonas pointed out.

**Closed** 2021-04-22 10:35 UTC
Labels: duplicate
